apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: stcs

resources:
  - namespace.yaml
  - secrets/database-secrets.yaml
  - configmaps/trino-config.yaml
  - configmaps/cube-config.yaml
  - configmaps/cube-models.yaml
  - deployments/postgres-cube.yaml
  - deployments/trino-coordinator.yaml
  - deployments/cube.yaml
  - ingress/ingress.yaml
  - monitoring.yaml

images:
  - name: trinodb/trino
    newTag: latest
  - name: cubejs/cube
    newTag: latest
  - name: postgres
    newTag: "15"

commonLabels:
  app.kubernetes.io/name: stcs
  app.kubernetes.io/instance: stcs-data-architecture
  app.kubernetes.io/version: "1.0.0"
  app.kubernetes.io/component: data-platform
  app.kubernetes.io/part-of: stcs-architecture

patches:
  - target:
      kind: Deployment
      name: trino-coordinator
    patch: |-
      - op: add
        path: /spec/template/metadata/annotations
        value:
          cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
  - target:
      kind: Deployment
      name: cube
    patch: |-
      - op: add
        path: /spec/template/metadata/annotations
        value:
          cluster-autoscaler.kubernetes.io/safe-to-evict: "true"