apiVersion: v1
kind: ConfigMap
metadata:
  name: cube-models
  namespace: stcs
data:
  customers.yml: |
    cubes:
      - name: customers
        sql_table: postgresql.public.customers

        joins: []

        dimensions:
          - name: customer_id
            sql: customer_id
            type: number
            primary_key: true

          - name: lead_score
            sql: lead_score
            type: number

          - name: external_id
            sql: external_id
            type: string

          - name: first_name
            sql: first_name
            type: string

          - name: last_name
            sql: last_name
            type: string

          - name: email
            sql: email
            type: string

          - name: phone
            sql: phone
            type: string

          - name: mobile_phone
            sql: mobile_phone
            type: string

          - name: company
            sql: company
            type: string

          - name: job_title
            sql: job_title
            type: string

          - name: department
            sql: department
            type: string

          - name: industry
            sql: industry
            type: string

          - name: website
            sql: website
            type: string

          - name: linkedin_profile
            sql: linkedin_profile
            type: string

          - name: twitter_handle
            sql: twitter_handle
            type: string

          - name: address_line1
            sql: address_line1
            type: string

          - name: address_line2
            sql: address_line2
            type: string

          - name: city
            sql: city
            type: string

          - name: state
            sql: state
            type: string

          - name: postal_code
            sql: postal_code
            type: string

          - name: country
            sql: country
            type: string

          - name: timezone
            sql: timezone
            type: string

          - name: lead_source
            sql: lead_source
            type: string

          - name: lead_status
            sql: lead_status
            type: string

          - name: notes
            sql: notes
            type: string

          - name: tags
            sql: tags
            type: string

          - name: is_active
            sql: is_active
            type: boolean

          - name: metadata
            sql: metadata
            type: string

          - name: created_at
            sql: created_at
            type: time

          - name: updated_at
            sql: updated_at
            type: time

          - name: last_contacted_at
            sql: last_contacted_at
            type: time

        measures:
          - name: count
            type: count
          
          - name: active_customers
            type: count
            filters:
              - sql: "{CUBE.is_active} = true"
          
          - name: avg_lead_score
            type: avg
            sql: lead_score

        pre_aggregations:
          - name: customers_rollup
            measures:
              - count
              - active_customers
              - avg_lead_score
            dimensions:
              - lead_status
              - lead_source
              - country
              - industry
            time_dimension: created_at
            granularity: month
            partition_granularity: month
            refresh_key:
              every: 1 hour