views:
  - name: inventory_management
    description: "Comprehensive view for inventory tracking and management"

    cubes:
      # Base products cube
      - join_path: products
        includes:
          - product_id
          - product_name
          - sku
          - category
          - subcategory
          - brand
          - price
          - cost
          - inventory_quantity
          - reorder_level
          - is_active
          - count
          - total_inventory_value
          - avg_price
          - avg_cost
          - total_inventory_quantity
          - products_below_reorder

      # Order items to track product sales
      - join_path: order_items
        prefix: true
        includes:
          - count
          - total_quantity
          - total_amount
          - created_at